select * from customer limit 20

--Q1. What is total revenue generated by male vs. female custo

SELECT "Gender",
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";
--Q2. which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >
(
    SELECT AVG("Purchase Amount (USD)")
    FROM customer
);


--Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    "Item Purchased",
    AVG("Review Rating") AS avg_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;


--Q4. Compare the avearage Purchase Amounts between Standard and Express shipping?
SELECT 
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS avg_purchase
FROM customer
GROUP BY "Shipping Type";

--Q5. Which 5 products ahve the highest percentage of purchases with discount applied?


SELECT 
    "Item Purchased",
    COUNT(*) * 100.0 / 
    (
        SELECT COUNT(*)
        FROM customer
        WHERE "Discount Applied" = 'Yes'
    ) AS discount_percentage
FROM customer
WHERE "Discount Applied" = 'Yes'
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;


--Q6. What are the top 3 most purchaseed products within each category ?

SELECT *
FROM
(
    SELECT 
        "Category",
        "Item Purchased",
        COUNT(*) AS total_purchases,
        
        RANK() OVER
        (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS rank_num

    FROM customer
    GROUP BY "Category", "Item Purchased"
) ranked_products

WHERE rank_num <= 3;


--Q7. Are customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
SELECT 
    "Subscription Status",
    COUNT(*) AS customer_count
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";


--Q9. What are the  revenue contribution of each age group?
SELECT 
    CASE
    
        WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
        WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
        WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
        WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
        
    END AS age_group,

    SUM("Purchase Amount (USD)") AS total_revenue

FROM customer

GROUP BY age_group

ORDER BY total_revenue DESC;
